// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type CreateUserParams struct {
	Name string    `json:"name"`
	DOB  time.Time `json:"dob"`
}

type UpdateUserParams struct {
	ID   int32     `json:"id"`
	Name string    `json:"name"`
	DOB  time.Time `json:"dob"`
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob) VALUES ($1, $2)
RETURNING id, name, dob
`

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.DOB)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DOB)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, dob FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DOB)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.DOB); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, dob = $3 WHERE id = $1
RETURNING id, name, dob
`

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.DOB)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DOB)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}
